apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: demo } }
  template:
    metadata: { labels: { app: demo } }
    spec:
      containers:
        - name: demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [ { containerPort: 8080 } ]
          readinessProbe: { httpGet: { path: "/", port: 8080 }, initialDelaySeconds: 5 }
          livenessProbe:  { httpGet: { path: "/", port: 8080 }, initialDelaySeconds: 10 }
