apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: demo }
  ports: [ { port: {{ .Values.service.port }}, targetPort: 8080 } ]
